//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

typedef struct {
    unsigned int _field1;
    int _field2;
    long long _field3;
    unsigned long long _field4;
    unsigned long long _field5;
    int _field6;
} CDStruct_9227e8cc;

typedef struct {
    unsigned long long _field1;
    unsigned long long _field2;
    id _field3;
    char _field4;
    char _field5;
    char _field6;
} ProgressReturnType;

@protocol ExportImageProtocol
- (struct CGSize)lastExportedImageSize;
- (BOOL)exportImageAtIndex:(unsigned long long)arg1 dest:(NSString *)arg2 options:(CDStruct_9227e8cc *)arg3;
- (unsigned long long)sessionID;
- (NSString *)directoryPath;
- (void)cancelExportBeforeBeginning;
- (void)startExport;
- (void)clickExport;
- (void)disableControls;
- (void)enableControls;
- (id)window;
- (NSString *)eventNameAtIndex:(unsigned long long)arg1;
- (unsigned long long)eventIndexForImageAtIndex:(unsigned long long)arg1;
- (unsigned long long)eventCount;
- (unsigned long long)positionOfImageAtIndex:(unsigned long long)arg1 inAlbum:(unsigned long long)arg2;
- (NSString *)albumCommentsAtIndex:(unsigned long long)arg1;
- (NSString *)albumMusicPathAtIndex:(unsigned long long)arg1;
- (NSString *)albumNameAtIndex:(unsigned long long)arg1;
- (unsigned long long)imageCountAtAlbumIndex:(unsigned long long)arg1;
- (unsigned long long)albumCount;
- (unsigned int)getImageFormatForExtension:(NSString *)arg1;
- (NSString *)getExtensionForImageFormat:(unsigned int)arg1;
- (NSArray *)albumsOfImageAtIndex:(unsigned long long)arg1;
- (NSArray *)imageKeywordsAtIndex:(unsigned long long)arg1;
- (NSDictionary *)imageExifPropertiesAtIndex:(unsigned long long)arg1;
- (NSDictionary *)imageTiffPropertiesAtIndex:(unsigned long long)arg1;
- (long long)imageRatingAtIndex:(unsigned long long)arg1;
- (NSDate *)imageDateAtIndex:(unsigned long long)arg1;
- (unsigned long long)imageFileSizeAtIndex:(unsigned long long)arg1;
- (double)imageAspectRatioAtIndex:(unsigned long long)arg1;
- (BOOL)imageIsPortraitAtIndex:(unsigned long long)arg1;
- (BOOL)imageIsEditedAtIndex:(unsigned long long)arg1;
- (NSString *)imageFileNameAtIndex:(unsigned long long)arg1;
- (NSString *)thumbnailPathAtIndex:(unsigned long long)arg1;
- (NSString *)sourcePathAtIndex:(unsigned long long)arg1;
- (NSString *)imagePathAtIndex:(unsigned long long)arg1;
- (long long)imageRotationAtIndex:(unsigned long long)arg1;
- (NSString *)imageCommentsAtIndex:(unsigned long long)arg1;
- (NSString *)imageTitleAtIndex:(unsigned long long)arg1;
- (BOOL)originalIsMovieAtIndex:(unsigned long long)arg1;
- (BOOL)originalIsRawAtIndex:(unsigned long long)arg1;
- (unsigned int)originalImageFormatAtIndex:(unsigned long long)arg1;
- (unsigned int)imageFormatAtIndex:(unsigned long long)arg1;
- (struct CGSize)imageSizeAtIndex:(unsigned long long)arg1;
- (unsigned long long)imageCount;
@end

@protocol ExportPluginBoxProtocol
- (BOOL)performKeyEquivalent:(NSEvent *)arg1;
@end

@protocol ExportPluginProtocol
- (NSString *)name;
- (void)cancelExport;
- (void)unlockProgress;
- (void)lockProgress;
- (ProgressReturnType *)progress;
- (void)performExport:(NSString *)arg1;
- (void)startExport:(NSString *)arg1;
- (void)clickExport;
- (BOOL)validateUserCreatedPath:(NSString *)arg1;
- (BOOL)handlesMovieFiles;
- (BOOL)treatSingleSelectionDifferently;
- (NSString *)defaultDirectory;
- (NSString *)defaultFileName;
- (NSString *)getDestinationPath;
- (BOOL)wantsDestinationPrompt;
- (NSString *)requiredFileType;
- (void)viewWillBeDeactivated;
- (void)viewWillBeActivated;
- (NSView *)firstView;
- (NSView<ExportPluginBoxProtocol> *)settingsView;
- (id)initWithExportImageObj:(id <ExportImageProtocol>)arg1;
@end

@interface ExportController : NSObject <NSOpenSavePanelDelegate>
{
    id mWindow;
    id mExportView;
    NSButtonCell *mExportButton;
    NSTextField *mImageCount;
    BOOL mCurrentPluginHandlesMovies;
    BOOL mCancelExport;
    NSTimer *mTimer;
    NSString *mDirectoryPath;
    NSMutableArray *mExportPanelNibObjects;
}

- (id)_selectableExportPathForPath:(id)arg1;
- (void)_updateImageCount;
- (void)_resizeExporterToFitView:(id)arg1;
- (BOOL)_hasPlugins;
- (id)exportView;
- (void)selectExporter:(id)arg1;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)tabView:(id)arg1 willSelectTabViewItem:(id)arg2;
- (void)disableControls;
- (id)window;
- (void)enableControls;
- (void)cancel:(id)arg1;
- (void)progressCanceled:(id)arg1;
- (void)progressCompleted:(id)arg1;
- (void)startExport:(id)arg1;
- (void)_exportProgress:(id)arg1;
- (void)_exportThread:(id)arg1 directoryPath:(id)arg2;
- (void)export:(id)arg1;
- (BOOL)filesWillFitOnDisk;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (void)show;
- (void)setDirectoryPath:(id)arg1;
- (id)directoryPath;
- (BOOL)currentPluginHandlesMovies;
- (void)setCurrentPluginRec:(id)arg1;
- (id)currentPluginRec;
- (id)currentPlugin;
- (void)dealloc;
- (void)awakeFromNib;

@end


@interface ExportMgr : NSObject <ExportImageProtocol>
{
    NSMutableArray *mExporters;
    NSArray *mSelectedAlbumsArray;
    NSArray *mRepresentedEventsArray;
    struct IPPhotoList *mSelection;
    struct IPPhotoList *mMovieSelection;
    struct IPAlbumList *mSelectedAlbums;
    ExportController *mExportController;
    NSString *mOriginalDateFormatString;
    NSString *mDateTimeFormat;
    unsigned long long mSessionID;
    struct CGSize mLastExportSize;
}

+ (struct CGSize)exportImage:(struct IPPhotoInfo *)arg1 dest:(id)arg2 format:(unsigned int)arg3 quality:(double)arg4 rotation:(long long)arg5 width:(unsigned long long)arg6 height:(unsigned long long)arg7 metadata:(int)arg8;
+ (id)gpsPropertyChangesIncludeGPS:(BOOL)arg1 withLatitude:(id)arg2 longitude:(id)arg3 altitude:(id)arg4;
+ (id)iptcPropertyChangesIncludeMetadata:(BOOL)arg1 withTitle:(id)arg2 comment:(id)arg3 keywords:(id)arg4;
+ (id)exportMgrNoAlloc;
+ (id)exportMgr;
- (BOOL)_checkForChangedDateLayout;
- (struct CGSize)lastExportedImageSize;
- (BOOL)exportImageAtIndex:(unsigned long long)arg1 dest:(id)arg2 options:(CDStruct_9227e8cc *)arg3;
- (unsigned int)getImageFormatForExtension:(id)arg1;
- (id)getExtensionForImageFormat:(unsigned int)arg1;
- (id)validFilename:(id)arg1;
- (BOOL)ensurePermissions:(unsigned long long)arg1 forPath:(id)arg2;
- (id)stringByResolvingAliasesInPath:(id)arg1;
- (id)pathContentOfAliasAtPath:(id)arg1;
- (BOOL)isAliasFileAtPath:(id)arg1;
- (unsigned long long)sizeAtPath:(id)arg1 count:(unsigned long long *)arg2 physical:(BOOL)arg3;
- (unsigned long long)countFilesFromArray:(id)arg1 descend:(BOOL)arg2;
- (unsigned long long)countFiles:(id)arg1 descend:(BOOL)arg2;
- (id)pathForFSRef:(struct FSRef *)arg1;
- (BOOL)getFSRef:(struct FSRef *)arg1 forPath:(id)arg2 isDirectory:(BOOL)arg3;
- (id)makeUniqueFileNameWithTime:(id)arg1;
- (id)makeUniqueFilePath:(id)arg1 extension:(id)arg2;
- (id)makeUniquePath:(id)arg1;
- (id)uniqueSubPath:(id)arg1 child:(id)arg2;
- (BOOL)createDir:(id)arg1;
- (BOOL)doesDirectoryExist:(id)arg1;
- (BOOL)doesFileExist:(id)arg1;
- (id)temporaryDirectory;
- (unsigned long long)sessionID;
- (id)directoryPath;
- (void)markFilesExported;
- (void)cancelExportBeforeBeginning;
- (void)cancelExport;
- (void)startExport;
- (void)clickExport;
- (id)window;
- (void)disableControls;
- (void)enableControls;
- (struct IPPhotoInfo *)photoAtIndex:(unsigned long long)arg1;
- (id)eventNameAtIndex:(unsigned long long)arg1;
- (unsigned long long)eventIndexForImageAtIndex:(unsigned long long)arg1;
- (unsigned long long)eventCount;
- (unsigned long long)positionOfImageAtIndex:(unsigned long long)arg1 inAlbum:(unsigned long long)arg2;
- (id)albumsOfImageAtIndex:(unsigned long long)arg1;
- (id)albumCommentsAtIndex:(unsigned long long)arg1;
- (id)albumMusicPathAtIndex:(unsigned long long)arg1;
- (id)albumNameAtIndex:(unsigned long long)arg1;
- (unsigned long long)imageCountAtAlbumIndex:(unsigned long long)arg1;
- (unsigned long long)albumCount;
- (BOOL)commitImageRotation;
- (id)imageFileNameAtIndex:(unsigned long long)arg1;
- (id)imageKeywordsAtIndex:(unsigned long long)arg1;
- (id)imageExifPropertiesAtIndex:(unsigned long long)arg1;
- (id)imageTiffPropertiesAtIndex:(unsigned long long)arg1;
- (long long)imageRatingAtIndex:(unsigned long long)arg1;
- (id)imageDateAtIndex:(unsigned long long)arg1;
- (unsigned long long)imageFileSizeAtIndex:(unsigned long long)arg1;
- (double)imageAspectRatioAtIndex:(unsigned long long)arg1;
- (id)thumbnailPathAtIndex:(unsigned long long)arg1;
- (long long)imageRotationAtIndex:(unsigned long long)arg1;
- (id)imageCommentsAtIndex:(unsigned long long)arg1;
- (id)imageTitleAtIndex:(unsigned long long)arg1;
- (BOOL)originalIsMovieAtIndex:(unsigned long long)arg1;
- (BOOL)originalIsRawAtIndex:(unsigned long long)arg1;
- (unsigned int)originalImageFormatAtIndex:(unsigned long long)arg1;
- (unsigned int)imageFormatAtIndex:(unsigned long long)arg1;
- (struct CGSize)imageSizeAtIndex:(unsigned long long)arg1;
- (id)sourcePathAtIndex:(unsigned long long)arg1;
- (id)imagePathAtIndex:(unsigned long long)arg1;
- (BOOL)imageIsPortraitAtIndex:(unsigned long long)arg1;
- (BOOL)imageIsEditedAtIndex:(unsigned long long)arg1;
- (unsigned long long)imageCount;
- (void)scanForExporters;
- (void)scanForExportersInDirectory:(id)arg1 foundBundleIDs:(id)arg2 foundExporters:(id)arg3;
- (id)recAtIndex:(unsigned long long)arg1;
- (unsigned long long)count;
- (void)updateDocumentSelection;
- (id)document;
- (void)setDocument:(id)arg1;
- (id)exportController;
- (void)setExportController:(id)arg1;
- (void)releasePlugins;
- (void)dealloc;
- (id)init;

@end

